In [2]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [3]:
analytics_document = nlp("He is reading books with other students while eating meal.")

In [ ]:
for token in analytics_document:
    print(token.text, token.lemma_, token.is_stop)

In [7]:
txt = "This is the first sentence. However, all the other Ph.D. students are working on , say , second sentence."

txt_analytics = nlp(txt)
for sentence in txt_analytics.sents:
    print(sentence, type(sentence))


This is the first sentence. <class 'spacy.tokens.span.Span'>
However, all the other Ph.D. students are working on , say , second sentence. <class 'spacy.tokens.span.Span'>


In [9]:
def nGrams(doc_string_or_list, n, docIsAlreadyTokenized):
    doc = doc_string_or_list
    if not docIsAlreadyTokenized:
        doc = [token.text for token in nlp(doc_string_or_list)]
    doc = " ".join(doc).lower().split(' ')
    grams = [doc[i:i+n] for i in range(len(doc)-n+1)]
    return grams

In [19]:
doc = "how old are you today or can you tell me something about you"
n = 2

# n = 1 : 유니그램 (unigram)
# n = 2 : 바이그램 (bigram)
# n = 3 : 트라이그램 (trigram)
# n >= 4 : n-gram

grams = nGrams(doc, n, False)

In [20]:
grams

[['how', 'old'],
 ['old', 'are'],
 ['are', 'you'],
 ['you', 'today'],
 ['today', 'or'],
 ['or', 'can'],
 ['can', 'you'],
 ['you', 'tell'],
 ['tell', 'me'],
 ['me', 'something'],
 ['something', 'about'],
 ['about', 'you']]

In [21]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [22]:
L = list(nlp.vocab.strings)
numWords = len(L)
print(numWords)

83814


In [23]:
import numpy  as np

L = list(nlp.vocab.strings)
numWords = len(L)

W2I = dict(zip(L, np.arange(numWords)))
I2W = dict(zip(np.arange(numWords), L))

In [ ]:
print(L)
np.arange(numWords)

In [27]:
W2I["game"]

49410

In [28]:
I2W[49410]

'game'

In [36]:
def oneHotVector(word, W2I, numWords):
    v = np.zeros(numWords)
    v[W2I[word]] = 1
    return v

In [37]:
v = oneHotVector("game", W2I, numWords)
v, v.shape, v[49410], v[W2I["game"]]

(array([0., 0., 0., ..., 0., 0., 0.]), (83814,), 1.0, 1.0)

In [69]:
doc = "How are you today. I know most of the time how you feel. ."

# 이 doc을 토큰화한 다음 리스트로 만들어 보세요
tokens = [token.text for token in nlp(doc)]
print(tokens)
numWords = len(tokens)
print(numWords)


W2I = dict(zip(tokens, np.arange(numWords)))
I2W = dict(zip(np.arange(numWords), tokens))
print(W2I["feel"])
print(I2W[14])

['How', 'are', 'you', 'today', '.', 'I', 'know', 'most', 'of', 'the', 'time', 'how', 'you', 'feel', '.', '.']
16
13
.


In [66]:
v = np.zeros(numWords)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
for token in tokens:
    v += oneHotVector(token, W2I, numWords)

In [68]:
v

array([1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 2., 1., 0., 3.])